insert into song (title, artist, album, release_year) values('Private Show', 'Britney Spears', 'Glory', 2016);
insert into song (title, artist, album, release_year) values('7 Years', 'Lukas Graham', 'Lukas Graham (Blue Album)', 2015);
insert into song (title, artist, album, release_year) values('No', 'Meghan Trainor', 'Thank You', 2016);
insert into song (title, artist, album, release_year) values('I hate u, I love u', 'Gnash', 'Top Hits 2017', 2017);
insert into song (title, artist, album, release_year) values('I Took a Pill in Ibiza', 'Mike Posner', 'At Night, Alone.', 2016);
insert into song (title, artist, album, release_year) values('Bad Things', 'Camila Cabello, Machine Gun Kelly', 'Bloom', 2017);
insert into song (title, artist, album, release_year) values('Ghostbusters (I am not a fraid)', 'Fall Out Boy, Missy Elliott', 'Ghostbusters', 2016);
insert into song (title, artist, album, release_year) values('Team', 'Iggy Azalea', 'No Album', 2016);
insert into song (title, artist, album, release_year) values('Mom', 'Meghan Trainor, Kelli Trainor', 'Thank You', 2016);
insert into song (title, artist, album, release_year) values('Cant Stop the Feeling', 'Justin Timberlake', 'Trolls', 2016);
insert into user (user_id, first_name, last_name, email) values('me', 'Me', 'Myself', 'me@web.de');
insert into user (user_id, first_name, last_name, email) values('eschuler', 'Elena', 'Schuler', 'eschuler@web.de');
insert into user (user_id, first_name, last_name, email) values('mmuster', 'Maxime', 'Muster', 'mmuster@web.de');
insert into songlist(owner, access) values(1, 1);
insert into songlist(owner, access) values(1, 0);
insert into songlist(owner, access) values(1, 1);
insert into songlist(owner, access) values(2, 1);
insert into songlist(owner, access) values(2, 0);
insert into songlist(owner, access) values(2, 0);
insert into songlist(owner, access) values(2, 1);
insert into songlist(owner, access) values(3, 1);
insert into songlist(owner, access) values(3, 0);
insert into playlistEntries values(1, 1);
insert into playlistEntries values(1, 2);
insert into playlistEntries values(1, 9);
insert into playlistEntries values(1, 6);
insert into playlistEntries values(2, 2);
insert into playlistEntries values(2, 5);
insert into playlistEntries values(2, 7);
insert into playlistEntries values(2, 6);
insert into playlistEntries values(3, 10);
insert into playlistEntries values(3, 8);
insert into playlistEntries values(3, 3);
insert into playlistEntries values(4, 4);
insert into playlistEntries values(4, 1);
insert into playlistEntries values(4, 9);
insert into playlistEntries values(5, 5);
insert into playlistEntries values(5, 6);
insert into playlistEntries values(5, 2);
insert into playlistEntries values(6, 6);
insert into playlistEntries values(6, 3);
insert into playlistEntries values(7, 7);
insert into playlistEntries values(7, 8);
insert into playlistEntries values(7, 4);
insert into playlistEntries values(8, 5);
insert into playlistEntries values(8, 8);
insert into playlistEntries values(9, 9);
insert into playlistEntries values(9, 5);
insert into playlistEntries values(9, 1);